# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# count_overlapping_polygons_from_script.py
# Created on: 2016-09-09 17:04:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: count_overlapping_polygons_from_script <Input_Features> <Expression> <Output_Feature_Class> 
# Description: 
# Given a polygon feature class or layer containing overlapping polygons, creates a new feature class with the overlaps removed and the number of overlapping polygons.
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
Input_Features = arcpy.GetParameterAsText(0)

Expression = arcpy.GetParameterAsText(1)
if Expression == '#' or not Expression:
    Expression = "Join_Count = 0" # provide a default value if unspecified

Output_Feature_Class = arcpy.GetParameterAsText(2)

# Local variables:
Spaghetti = Input_Features
oidfield = Spaghetti
features_to_delete = oidfield
in_memory_feature = features_to_delete
output_value = in_memory_feature
Meatballs = Spaghetti
count_overlaps = Meatballs
Spaghetti_2 = Spaghetti
in_memory = "in_memory"
Features_to_Delete = Expression
Features_Deleted = Features_to_Delete
Delete_succeeded = Features_Deleted
empty = "in_memory\\empty"

# Process: Create Feature Class
arcpy.CreateFeatureclass_management(in_memory, "empty", "POINT", "", "DISABLED", "DISABLED", "", "", "0", "0", "0")

# Process: Feature To Polygon
arcpy.FeatureToPolygon_management("''", Spaghetti, "", "NO_ATTRIBUTES", empty)

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(Spaghetti, Spaghetti_2, "", "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE")

# Process: Calculate Value
arcpy.CalculateValue_management("GetOidFieldName(r\"%Spaghetti%\")", "import arcpy\\ndef GetOidFieldName(path):\\n  fc = arcpy.Describe(path)\\n  return fc.oidfieldname\\n\\n  ", "Field")

# Process: Feature To Point
arcpy.FeatureToPoint_management(Spaghetti, Meatballs, "INSIDE")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(Meatballs, Input_Features, count_overlaps, "JOIN_ONE_TO_ONE", "KEEP_ALL", "", "WITHIN", "", "")

# Process: Add Join
arcpy.AddJoin_management(Spaghetti_2, oidfield, count_overlaps, "ORIG_FID", "KEEP_ALL")

# Process: Copy Features in memory
arcpy.CopyFeatures_management(features_to_delete, in_memory_feature, "", "0", "0", "0")

# Process: Python script - rename field
arcpy.CalculateValue_management("getFieldNames(r'in_memory\\temporary_feature_class_for_field_altering')", "def getFieldNames(shp):\\n    for field in arcpy.ListFields(shp):\\n        if field.name in [\"overlap_count_OBJECTID\", \"overlap_count_TARGET_FID\", \"overlap_count_ORIG_FID\"]:\\n            arcpy.DeleteField_management(shp, field.name)\\n        elif field.name in ['FID', 'OBJECTID', 'Shape', 'Shape_Length', 'Shape_Area']:\\n            pass\\n        else:\\n            arcpy.AlterField_management(shp, field.name, field.name.replace('overlap_count_', ''))\\n            print field.name, field.name.replace('overlap_count_', '')\\n    return 1\\n", "Variant")

# Process: Copy Features
arcpy.CopyFeatures_management(in_memory_feature, Output_Feature_Class, "", "0", "0", "0")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Output_Feature_Class, Features_to_Delete, Expression, "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;overlap_count_OBJECTID overlap_count_OBJECTID VISIBLE NONE;overlap_count_Join_Count overlap_count_Join_Count VISIBLE NONE;overlap_count_TARGET_FID overlap_count_TARGET_FID VISIBLE NONE;overlap_count_ORIG_FID overlap_count_ORIG_FID VISIBLE NONE;overlap_count_ID overlap_count_ID VISIBLE NONE;overlap_count_DATE overlap_count_DATE VISIBLE NONE;overlap_count_TIME overlap_count_TIME VISIBLE NONE;overlap_count_SATELLITE overlap_count_SATELLITE VISIBLE NONE;overlap_count_SENSOR overlap_count_SENSOR VISIBLE NONE;overlap_count_SPECTR_RNG overlap_count_SPECTR_RNG VISIBLE NONE;overlap_count_SPATIAL_RE overlap_count_SPATIAL_RE VISIBLE NONE;overlap_count_CLOUD_PRCN overlap_count_CLOUD_PRCN VISIBLE NONE;overlap_count_FILE_FORMT overlap_count_FILE_FORMT VISIBLE NONE;overlap_count_PROCES_LVL overlap_count_PROCES_LVL VISIBLE NONE;overlap_count_ARCHIVE overlap_count_ARCHIVE VISIBLE NONE")

# Process: Delete Features
arcpy.DeleteFeatures_management(Features_to_Delete)

# Process: Delete
arcpy.Delete_management(Features_to_Delete, "")

